#!/usr/bin/env bash
set -euo pipefail

swww-daemon --format argb &
udiskie &
swaync &
hypridle &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
swayosd-server &
easyeffects --gapplication-service &
"$HOME"/.config/hypr/scripts/portal &
vicinae server &
# Quickshell (dock only — bar is disabled in panelFamilies/IllogicalImpulseFamily.qml)
qs -c ii &
pypr &
wl-paste --watch cliphist store &
