#!/usr/bin/env bash
set -euo pipefail

floating=$(hyprctl activewindow -j | jq '.floating')
window=$(hyprctl activewindow -j | jq -r '.initialClass')

default_width="${1:-70%}"
default_height="${2:-70%}"

function toggle() {
  width=$1
  height=$2

  hyprctl --batch "dispatch togglefloating; dispatch resizeactive exact ${width} ${height}; dispatch centerwindow"
}

function untoggle() {
  hyprctl dispatch togglefloating
}

function handle() {
  width=$1
  height=$2

  if [ "$floating" == "false" ]; then
    toggle "$width" "$height"
  else
    untoggle
  fi
}

case $window in
kitty) handle "50%" "55%" ;;
*) handle "$default_width" "$default_height" ;;
esac

