decoration {
    rounding = 4

    active_opacity = 1
    inactive_opacity = 1

    blur {
        enabled = yes
        size = 5
        passes = 4
        ignore_opacity = true
        xray = false
        noise = 0.0
        popups = true
    }

    shadow {
        enabled = false
        range = 10
        scale = 2
        render_power = 5
        color = rgb(363a4f)
        color_inactive = rgb(181926)
    }

    dim_inactive = false
    dim_strength = 0.05
}

group {
    col.border_inactive = rgba(b7bdf869)
    col.border_active = rgba(cad3f5ee) rgba(b7bdf869) rgba(b7bdf869) rgba(cad3f5ee) 45deg
    col.border_locked_inactive = rgba(b7bdf869)
    col.border_locked_active = rgba(cad3f5ee) rgba(b7bdf869) rgba(b7bdf869) rgba(cad3f5ee) 45deg

    groupbar {
        gradients = true
        gradient_rounding = 7
        indicator_height = 0
        gradient_round_only_edges = true
        col.active = rgba(b7bdf8CC)
        col.inactive = rgba(b8c0e099)
        col.locked_active = rgba(ee99a0CC)
        col.locked_inactive = rgba(b8c0e099)
        font_family = Berkeley Mono
        font_size = 15
        text_color = rgb(181926)
        height = 20
    }
}
