$launcher = vicinae
$launcher_toggle = $launcher toggle
$launcher_windows = $launcher vicinae://extensions/vicinae/wm/switch-windows
$launcher_clipboard = $launcher vicinae://extensions/vicinae/clipboard/history
$launcher_emojis = $launcher vicinae://extensions/vicinae/core/search-emojis
$launcher_icons = $launcher vicinae://extensions/destiner/iconify/search-icons
$launcher_gifs = $launcher vicinae://extensions/josephschmitt@raycast/gif-search/search
$launcher_players = $launcher vicinae://extensions/dagimg-dot/player-pilot/player-pilot
$launcher_wallpapers = $launcher vicinae://extensions/sovereign/awww-switcher/wpgrid
$launcher_weather = $launcher vicinae://extensions/tonka3000/weather/index
$launcher_time = $launcher vicinae://extensions/joao.mainka/raycast-timezone-converter/index
$launcher_pass = $launcher vicinae://extensions/jomifepe/bitwarden/search
$launcher_shortcuts = $launcher vicinae://extensions/vicinae/manage-shortcuts/manage
$launcher_translate = $launcher vicinae://extensions/gebeto/translate/translate
$launcher_bluetooth = $launcher vicinae://extensions/Gelei/bluetooth/devices
$launcher_random = $launcher vicinae://extensions/loris/random/index
$launcher_wifi = $launcher vicinae://extensions/dagimg-dot/wifi-commander/scan-wifi
$launcher_bookmarks = $launcher vicinae://extensions/luolei/karakeep/bookmarks
$launcher_screenshots = $launcher vicinae://extensions/piesinu/hyprshot-vicinae/make-screenshot
$launcher_color_picker = $launcher vicinae://extensions/psampir/color-picker/pick-color
