# Launcher
source = ~/.config/hypr/configs/launcher.conf

# Bar
$bar = waybar
$bar_toggle = killall -SIGUSR1 $bar
$bar_reload = killall $bar; $bar

# Notifications
$notifications_menu = swaync-client
$notifications_menu_read = $notifications_menu -C
$notifications_menu_toggle = $notifications_menu -t
$notifications_menu_disturb = $notifications_menu -d
$notifications_menu_reload = $notifications_menu -R && $notifications_menu -rs

# Terminal
$terminal = ghostty --gtk-single-instance=true
$terminal_float = $terminal --class=com.center-float

# Apps
$browser = zen-browser
$notetaking_app = obsidian
$office_suite = libreoffice
$editor = $terminal nvim
$alter_editor = vscodium
$file_manager = $terminal yazi
$alter_file_manager = nemo
$gaming_app = steam
$alter_gaming_app = flatpak run com.heroicgameslauncher.hgl
$daw = bitwig-studio
$recording_app = obs
$audio_effects = easyeffects
$music_player = feishin
