source = ~/.config/hypr/configs/default_apps.conf
source = ~/.config/hypr/configs/launcher.conf

$mainMod = SUPER
$scripts = ~/.config/hypr/scripts

# apps
bind = $mainMod, RETURN, exec, $scripts/launch_app $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, E, exec, $file-manager
bind = $mainMod, SPACE, exec, $launcher-toggle
bind = $mainMod, N, exec, $notifications-menu-toggle
bind = $mainMod, T, exec, $bar-toggle

# windows
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod, S, layoutmsg, togglesplit
bind = $mainMod SHIFT, S, layoutmsg, swapsplit
bind = $mainMod, A, exec, $scripts/toggle_floating 70% 70%
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, R, submap, resize
submap = resize
binde = , L, resizeactive, 40 0
binde = , RIGHT, resizeactive, 40 0
binde = , H, resizeactive, -40 0
binde = , LEFT, resizeactive, -40 0
binde = , K, resizeactive, 0 -40
binde = , UP, resizeactive, 0 -40
binde = , J, resizeactive, 0 40
binde = , DOWN, resizeactive, 0 40
bind = , ESCAPE, submap, reset
bind = , RETURN, submap, reset
submap = reset

# workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# scratchpads
bind = $mainMod, F1, togglespecialworkspace, volume
bind = $mainMod, F2, togglespecialworkspace, bluetooth
bind = $mainMod, F3, togglespecialworkspace, wifi
bind = $mainMod, F4, togglespecialworkspace, network

# media
bindl = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bindl = , XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle
bindle = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume +10
bindle = , XF86AudioLowerVolume, exec, swayosd-client --output-volume -10
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next
bindle = , XF86MonBrightnessUp, exec, swayosd-client --brightness +10
bindle = , XF86MonBrightnessDown, exec, swayosd-client --brightness -10
